#Current code generated by GPT-4
from django.db import models
from django.contrib.auth.models import User

# Models for User accounts to differentiate between
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True)
    ROLE_CHOICES = (
        ('customer', 'Customer'),
        ('owner', 'Restaurant Owner'),
        ('staff', 'Restaurant Staff'),
        ('admin', 'System Administrator'),
        ('developer', 'Developer'),
        ('marketing', 'Marketing Team Member'),
    )  
    role = models.CharField(max_length=50, choices=ROLE_CHOICES)
    

# Restaurant model
class Restaurant(models.Model):
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='owned_restaurants')
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    cuisine = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    opening_hours = models.CharField(max_length=100)
    contact_info = models.CharField(max_length=100)

# Menu model related to Restaurant
class Menu(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField(blank=True)

# Reservation model
class Reservation(models.Model):
    customer = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='reservations')
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    date_time = models.DateTimeField()
    party_size = models.IntegerField()
    special_requests = models.TextField(blank=True)
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('cancelled', 'Cancelled'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

# Review and Rating model
class Review(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='reviews')
    customer = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField()
    comments = models.TextField(blank=True)

# Promotion and Loyalty Program model
class Promotion(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='promotions')
    title = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    discount_rate = models.FloatField()

# Table model for managing table availability
class Table(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    capacity = models.IntegerField()
    is_available = models.BooleanField(default=True)

# Model for managing dining preferences and feedback for trend analysis
class DiningPreference(models.Model):
    customer = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    preferences = models.TextField()
    feedback = models.TextField(blank=True)