# Generated by Django 5.0.6 on 2024-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_diningpreference_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='loyality',
            field=models.IntegerField(default=0),
        ),
    ]
